Roll : 21226

Assignment 1 : Tensors

___

# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, tensors are used to encode the inputs and outputs of a model, as well as the model’s parameters.

1. Tensors are same as NumPy arrays, except that tensors can run on GPUs or other hardware accelerators.

2. Tensors and NumPy arrays share the same underlying memory, eliminating the need to copy data .

3. Tensors are optimized for automatic differentiation.

In [1]:
# PyTorch library import
import torch
import numpy as np

___

## How to initialize a tensor?
1. Direct Initialization.
2. Via a NumPy array.
3. Using another existing tensor.
4. Random initialization.

In [2]:
# Direct Initialization
direct_data = torch.tensor([[1,2], [2, 1]])
print(direct_data)

tensor([[1, 2],
        [2, 1]])


In [3]:
# NumPy init
arr = np.array([[1,2], [2,1]])
arr = torch.from_numpy(arr)
print(arr)

tensor([[1, 2],
        [2, 1]], dtype=torch.int32)


In [6]:
# From existing tensor

arr1 = torch.ones_like(arr)
print('Existing Tensor retaining its original properties:\n\n', arr1)

arr2 = torch.rand_like(arr, dtype = torch.float32)
print('\nOverriding torch.int32 to torch.float32:\n\n', arr2)

Existing Tensor retaining its original properties:

 tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

Overriding torch.int32 to torch.float32:

 tensor([[0.4352, 0.1283],
        [0.6029, 0.6531]])


In [7]:
# Random Init
shape = (4,5,) # Tensor of 4x5
tensor_rand = torch.rand(shape)
tensor_1 = torch.ones(shape)
tensor_0 = torch.zeros(shape)

print('Random Tensor in 4x5 : \n\n', tensor_rand)
print('\nTensor of ones in 4x5 : \n\n', tensor_1)
print('\nTensor of zeros in 4x5 : \n\n', tensor_0)

Random Tensor in 4x5 : 

 tensor([[0.5348, 0.0809, 0.5792, 0.2718, 0.2203],
        [0.7247, 0.7594, 0.5925, 0.2026, 0.2746],
        [0.0442, 0.6652, 0.8973, 0.6584, 0.9205],
        [0.7065, 0.0698, 0.8376, 0.4871, 0.8880]])

Tensor of ones in 4x5 : 

 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Tensor of zeros in 4x5 : 

 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


___

## Tensor Attributes

Every tensor has attributes such as:

    1. Shape
    2. Datatype
    3. Device

In [8]:
attrib_tensor = torch.rand(4,5)

print('Shape of tensor :', attrib_tensor.shape)
print('Data Type of tensor :', attrib_tensor.dtype)
print('Device Type of tensor :', attrib_tensor.device)

Shape of tensor : torch.Size([4, 5])
Data Type of tensor : torch.float32
Device Type of tensor : cpu


## Tensor Operations

1. Slicing
2. Indexing
3. Joining Tensors(concatination)
4. Arithmetic Operations of Tensors
5. Aggregation
6. In-place Operations

In [11]:
# Indexing
tensor = torch.ones(4,4,)
print('First Column: \n\n', tensor[:,0])
print('\nFirst Row: \n\n', tensor[0])
print('\nLast Row: \n\n', tensor[-1])
print('\nLast Column: \n\n', tensor[...,-1])

First Column: 

 tensor([1., 1., 1., 1.])

First Row: 

 tensor([1., 1., 1., 1.])

Last Row: 

 tensor([1., 1., 1., 1.])

Last Column: 

 tensor([1., 1., 1., 1.])


In [12]:
# Slicing
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
# Concat
t1 = torch.cat([tensor, tensor], dim =1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])


In [15]:
# Matrix Multiplication using Tensors
tensor @ tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [16]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [18]:
# Element-wise Product

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)

torch.mul(tensor, tensor, out = z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [21]:
# Aggregation and Numerical Value
print(tensor.sum(), ' : ' ,tensor.sum().item())

tensor(12.)  :  12.0


In [22]:
# In-Place Operations

print(tensor.add_(5))

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## NumPy and PyTorch Tensor memory relation

Tensors on CPU and NumPy arrays on the CPU share the same memory locations. Changing a tensor might change the ndarray and vice versa.

In [23]:
# Tensor to NumPy
t = torch.ones(9)
print('Tensor : ', t)

Tensor :  tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [24]:
n = t.numpy()
print('NumPy : ', n)

NumPy :  [1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
# Adding 1 to the Tensor
t.add_(1)
print('Tensor : ', t)
print('ndarray : ', n)

Tensor :  tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
ndarray :  [2. 2. 2. 2. 2.]


We can see that changing tensor, changed NumPy array as well. Similarly it happens for NumPy to Tensor as well.

In [28]:
# NumPy array to tensor
n = np.ones(5)
t = torch.from_numpy(n)

In [29]:
np.add(n, 1, out=n)
print('Tensor : ', t)
print('ndarray : ', n)

Tensor :  tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
ndarray :  [2. 2. 2. 2. 2.]


___

This marks the end of Tensor Assignment